[package]
name = "git_pull_approve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gix = "0.44.1"
dialoguer = "0.11.0"

