name: Rust
permissions: write-all
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy: 
      matrix:
        include:
          - os: macos-latest
            name: macos_x86_64
            target: x86_64-apple-darwin
          # - os: macos-latest
          #   name: macos_aarch64
          #   target: aarch64-apple-darwin
          - os: ubuntu-latest
            name: linux_x86_64
            target: x86_64-unknown-linux-gnu
          # - os: ubuntu-latest
          #   name: linux_aarch64
          #   target: aarch64-unknown-linux-gnu
          - os: windows-latest
            name: windows_x86_64
            target: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v3
    - name: Install rust version
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: ${{matrix.target}}
    - uses: actions/checkout@v3
    - name: Install Dependencies
      if: ${{'aarch64-unknown-linux-gnu' == matrix.target}}
      run: sudo apt-get update && sudo apt-get install gcc-aarch64-linux-gnu
    - name: Run tests (Windows)
      if: startsWith(matrix.target, 'x86_64') && startsWith(matrix.name, 'windows')
      run: $env::github_token="${{secrets.GITHUB_TOKEN}}" && cargo test --verbose --release
    - name: Run tests (Unix)
      if: startsWith(matrix.target, 'x86_64') && (startsWith(matrix.name, 'ubuntu')||startsWith(matrix.name, 'macos'))
      run: github_token="${{secrets.GITHUB_TOKEN}}" cargo test --verbose --release
    - name: Build Release
      run: cargo build --verbose --release --target=${{matrix.target}}
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-${{matrix.name}}"
        prerelease: false
        title: "Latest Build ${{matrix.name}}"
        files: |
          target/${{matrix.target}}/release/gitty.exe
          target/${{matrix.target}}/release/gitty.so
          target/${{matrix.target}}/release/gitty